// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrVHHmldx_3I0hWpVoIbRmjEdjXHtQ9tI',
    appId: '1:819731042387:web:79361b7d8d6ce64b9c36a6',
    messagingSenderId: '819731042387',
    projectId: 'project3-f6c1b',
    authDomain: 'project3-f6c1b.firebaseapp.com',
    storageBucket: 'project3-f6c1b.appspot.com',
    measurementId: 'G-TQZV28PSXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNtLgyD-cXjMdl3fhAucN_DmuelBZWHPs',
    appId: '1:819731042387:android:c3c6481dfd9439a19c36a6',
    messagingSenderId: '819731042387',
    projectId: 'project3-f6c1b',
    storageBucket: 'project3-f6c1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIiVzcJZyoDfdP88ysjhuvLED5Lar8Xto',
    appId: '1:819731042387:ios:a1e3c23f51ce3e189c36a6',
    messagingSenderId: '819731042387',
    projectId: 'project3-f6c1b',
    storageBucket: 'project3-f6c1b.appspot.com',
    iosClientId: '819731042387-9cek47c7nd7qjv7bhngvqogek05o6c1n.apps.googleusercontent.com',
    iosBundleId: 'com.example.project3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIiVzcJZyoDfdP88ysjhuvLED5Lar8Xto',
    appId: '1:819731042387:ios:a1e3c23f51ce3e189c36a6',
    messagingSenderId: '819731042387',
    projectId: 'project3-f6c1b',
    storageBucket: 'project3-f6c1b.appspot.com',
    iosClientId: '819731042387-9cek47c7nd7qjv7bhngvqogek05o6c1n.apps.googleusercontent.com',
    iosBundleId: 'com.example.project3',
  );
}
